### ISSUE TITLE
[BOUNTY] Set Up Initial Standard Library

### ISSUE THREAD

**Issue by Dishpit** [Dishpit/Omega#84]
![Static Badge](https://img.shields.io/badge/BOUNTY-%2450-darkgreen)

will need to set up a `/stl` directory inside `/interpreter` and ensure the contents are packaged during compilation

desired spec:

```omega
#math;

var my_num = 42;
var new_num = math.double(my_num);
out new_num; // -> outputs 84
```

to start, let's get a very basic math stl set up.

stl files should be coded out in Omega - this way we can ensure further development of the language as a whole, and not rely so heavily on its source language

***

regarding the bounty, [dm me on twitter](https://x.com/Dishpit) so we can exchange payment info

**Comment by NaeemAdburRahman** [comment]
Hi, I am interesting this

**Comment by Dishpit** [comment]
> Hi, I am interesting this

feel free to submit a proposal PR for a solution; in the meantime, [message me here](https://x.com/Dishpit) to exchange payment info 🤘

**Comment by FL3X46** [comment]
hı can ı work on this ?
